[build]
  command = "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
